# Generated by Django 4.2.17 on 2025-01-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
    ]
