# Generated by Django 4.2.17 on 2025-02-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0002_remove_customuser_name_remove_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
