# Generated by Django 4.2.17 on 2025-02-08 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_date",
                    models.DateField(blank=True, default="2000-01-01", null=True),
                ),
                ("title", models.TextField(blank=True, max_length=250, null=True)),
                (
                    "main_character",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                (
                    "time_setting",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="story.genre"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_date",
                    models.DateField(blank=True, default="2000-01-01", null=True),
                ),
                (
                    "part",
                    models.IntegerField(
                        choices=[
                            (1, "exposition"),
                            (2, "rising action"),
                            (3, "climax"),
                            (4, "falling action"),
                            (5, "resolution"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "pending"), (2, "rejected"), (3, "accepted")]
                    ),
                ),
                ("text", models.TextField(blank=True, max_length=100000, null=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="story.story"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
