# Generated by Django 4.2.17 on 2025-03-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0002_story_suggested_keyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="exposition_summary",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
