# Generated by Django 4.2.17 on 2025-03-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0003_story_exposition_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="status",
            field=models.IntegerField(
                choices=[(1, "pending"), (2, "published")], default=1
            ),
        ),
    ]
