# Generated by Django 5.2 on 2025-08-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0006_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="genre_images/"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
